import dotenv from 'dotenv'

const ENV = dotenv.config({ path: `./.env.${process.env.NODE_ENV}` }).parsed

ENV.HAS_AUTH_SERVICE = JSON.parse(ENV.HAS_AUTH_SERVICE)
ENV.ALLOWED_ORIGINS = JSON.parse(ENV.ALLOWED_ORIGINS)
ENV.DATABASE = JSON.parse(ENV.DATABASE)
ENV.SESSION_KEYS = JSON.parse(ENV.SESSION_KEYS)
ENV.HAS_EMAIL_SERVICE = JSON.parse(ENV.HAS_EMAIL_SERVICE)
ENV.SMTP_USERS = JSON.parse(ENV.SMTP_USERS)
ENV.SMTP_HOSTS = JSON.parse(ENV.SMTP_HOSTS)

global.ENV = ENV
